### ISSUE TITLE
sharing more

### ISSUE THREAD

**Issue by xieyuheng** [quanbrew/neonao#1]
我之前想的项目叫 wikiwikibus

- 所见即所得的结构化 wiki
- 以 git 为数据库
- 支持 `.org` `.md` `.rst`
- 可以像 travis-ci 一样和 github 联合使用
  - 以替代 github 原生的 wiki

**Comment by xieyuheng** [comment]
我当时想的是赚钱, 方式是: 人们可以独立 host 自己的 wiki, 如果想在我的域名下 host, 我在边角打广告赚钱, 想要消除广告要付费.

**Comment by xieyuheng** [comment]
也许你能成功, 争取毕业的时候直接逃离 wage labor 的奴役 >_<

**Comment by quanbrew** [comment]
@xieyuheng 

谢谢啦，我已经工作了

这个是 GPL 项目，如果完成度足够高的话我会采用 [Pay what you want](https://en.wikipedia.org/wiki/Pay_what_you_want) 模式收费，嗯。

我现在也在苦恼数据储存，云端数据库的话文件管理比较受限，本地的话同步又有麻烦。

git 数据库的想法很好，只不过移动端访问/修改会很麻烦，搜索起来也很麻烦。

**Comment by xieyuheng** [comment]
不用 git 你就需要自己设计 version control, 或者放弃编辑历史的信息.
移动端访问, 修改, 搜索, github 的前端都能做到的.
